# -*- coding: utf-8 -*-
"""Las HISTORIAS propias de CANON, ESTEPA, ACROPOLIS y SECUOYA. Los cuatro
salieron clonados de DUNAS y contaban el mismo cuento (SIRA, la caravana de
Ammar, el pozo tapado) con otro paisaje. Aca cada uno tiene su gente, su
problema y su final, en los tres idiomas.

Cada mundo define:
  intro   : (titulo, texto) x3 idiomas
  sub     : la bajada del titulo del menu x3
  caps    : 6 capitulos x3 idiomas  -> (n, t, obj, objT, dT, d)
  npc     : dict clave -> [linea, linea, ...] x3
  gente   : los NPC que se plantan: (clave, nombre, lugar, dx, dz, giro, glb, retrato, tipo)
  mision  : (icono, cuantos, capIndice, que_dice_el_contador)
"""

# ---------------------------------------------------------------- CAÑÓN -----
CANON = {
 'sub': ['el cañón rojo · bajar al río y encontrar el paso',
         'the red canyon · get down to the river and find the crossing',
         'o cânion vermelho · descer ao rio e achar a passagem'],
 'intro': [
  ('Once del séptimo mes',
   'Sos TÁMAR, la que mide los pasos. Tu oficio\nes ir adelante y volver diciendo si el\nganado puede bajar o no.\n\nEsta vez bajaste sola y la crecida te dejó\ndel lado equivocado. Arriba, en el filo,\nnoventa cabezas esperan una respuesta.\n\nAbajo hay un paso. Lo usaron los que\ntallaron las manos en la cueva.\n\nEncontralo antes de que el río vuelva a subir.'),
  ('Eleventh of the seventh month',
   'You are TÁMAR, the one who measures the way.\nYour trade is to go ahead and come back saying\nwhether the herd can go down or not.\n\nThis time you went down alone and the flood\nleft you on the wrong side. Up on the rim,\nninety head are waiting for an answer.\n\nThere is a crossing down here. The people who\ncarved the hands in the cave used it.\n\nFind it before the river rises again.'),
  ('Onze do sétimo mês',
   'Você é TÁMAR, a que mede os passos. Seu ofício\né ir na frente e voltar dizendo se o gado\npode descer ou não.\n\nEsta vez desceu sozinha e a enchente te\ndeixou do lado errado. Lá em cima, na borda,\nnoventa cabeças esperam uma resposta.\n\nEmbaixo há uma passagem. Usaram-na os que\nesculpiram as mãos na caverna.\n\nAche-a antes que o rio suba de novo.'),
 ],
 'caps': [
  # es
  [('CAPÍTULO 1', 'LA PRIMERA MARCA', 'mojon', 'Bajá al talud y encontrá la primera marca',
    'Una flecha y tres puntos', 'Grabada en la roca, a la altura de la cara:\nuna flecha y tres puntos.\n\nNo señala el río. Señala PARALELO al río,\nhacia donde el agua no llega nunca.\n\nQuien la hizo no quería cruzar. Quería\nbajar sin mojarse.'),
   ('CAPÍTULO 2', 'EL CAMPAMENTO DEL TALUD', 'campamento', 'Encontrá el campamento del talud',
    'Cuerdas y una mula', 'Dos aleros de lona clavados a la pared y una\nmula atada corto, tranquila.\n\nYADRÉ baja piedra de acá desde los quince.\nDice que el paso existe pero que este año\nel río se comió el escalón de abajo.\n\n«Hay otro. Más arriba. Yo no lo encuentro.»'),
   ('CAPÍTULO 3', 'LA CIUDAD DE ABAJO', 'ruinas', 'Cruzá las casas de piedra del fondo',
    'Nadie se fue apurado', 'Casas cuadradas metidas en el hueco de la\npared, con los techos intactos.\n\nNo hay ceniza ni huesos ni puertas\nreventadas: se fueron caminando, con tiempo,\nllevándose las ollas.\n\nSabían cuándo el cañón deja de ser casa.'),
   ('CAPÍTULO 4', 'LA POZA DEL FONDO', 'oasis', 'Bajá a la poza del fondo',
    'Agua quieta', 'El río se ensancha y se aquieta en una poza\nverde, tan honda que no se ve el piso.\n\nDel otro lado, la pared tiene ESCALONES.\nTallados. Van hasta arriba.\n\nY están tapados por tres derrumbes.'),
   ('CAPÍTULO 5', 'LOS TRES DERRUMBES', 'oasis', 'Despejá los 3 derrumbes de la escalera', True,
    'La escalera entera', 'Piedra por piedra. Las grandes van al agua,\nlas chicas al montón.\n\nY aparece: una escalera de mil años, de un\nmetro de ancho, subiendo pegada a la pared\nhasta el filo.\n\nEl ganado va a pasar de a uno. Pero va a pasar.'),
   ('CAPÍTULO 6', 'EL BALCÓN', 'cresta', 'Subí a la boca del cañón y hacé la señal', True,
    'FIN', 'Desde la boca del cañón se ve el filo de\narriba, chiquito, con noventa puntos quietos.\n\nEncendés el trapo de aceite y lo giras tres\nveces: BAJEN, DE A UNO, POR EL ESTE.\n\nUn punto se separa de la fila. Después otro.\nDespués la fila entera, ordenada, empezando\na bajar por una escalera que no estaba.\n\nCAÑÓN — fin de la historia.')],
  # en
  [('CHAPTER 1', 'THE FIRST MARK', 'mojon', 'Get down the slope and find the first mark',
    'An arrow and three dots', 'Carved into the rock at face height:\nan arrow and three dots.\n\nIt does not point at the river. It points\nPARALLEL to it, where the water never reaches.\n\nWhoever cut it did not want to cross.\nThey wanted to get down without getting wet.'),
   ('CHAPTER 2', 'THE SLOPE CAMP', 'campamento', 'Find the camp on the slope',
    'Ropes and a mule', 'Two canvas lean-tos pinned to the wall and a\nmule tied short, calm.\n\nYADRÉ has been bringing stone down from here\nsince he was fifteen. He says the crossing\nexists but this year the river ate the bottom step.\n\n“There is another. Higher up. I cannot find it.”'),
   ('CHAPTER 3', 'THE TOWN BELOW', 'ruinas', 'Cross the stone houses at the bottom',
    'Nobody left in a hurry', 'Square houses set into the hollow of the wall,\nroofs intact.\n\nNo ash, no bones, no broken doors: they walked\nout, with time, taking the pots with them.\n\nThey knew when a canyon stops being a home.'),
   ('CHAPTER 4', 'THE DEEP POOL', 'oasis', 'Get down to the pool at the bottom',
    'Still water', 'The river widens and settles into a green pool,\nso deep you cannot see the floor.\n\nOn the far side the wall has STEPS.\nCut by hand. They go all the way up.\n\nAnd three rockfalls are covering them.'),
   ('CHAPTER 5', 'THE THREE ROCKFALLS', 'oasis', 'Clear the 3 rockfalls off the stair', True,
    'The whole stair', 'Stone by stone. Big ones into the water,\nsmall ones onto the pile.\n\nAnd there it is: a thousand-year stair, a metre\nwide, climbing tight against the wall\nall the way to the rim.\n\nThe herd will pass one at a time. But it will pass.'),
   ('CHAPTER 6', 'THE BALCONY', 'cresta', 'Climb to the canyon mouth and give the signal', True,
    'THE END', 'From the canyon mouth you can see the rim above,\ntiny, with ninety still dots on it.\n\nYou light the oiled rag and swing it three\ntimes: COME DOWN, ONE BY ONE, ON THE EAST.\n\nOne dot leaves the line. Then another.\nThen the whole line, in order, starting down\na stair that was not there.\n\nCANYON — end of the story.')],
  # pt
  [('CAPÍTULO 1', 'A PRIMEIRA MARCA', 'mojon', 'Desça o talude e ache a primeira marca',
    'Uma flecha e três pontos', 'Gravada na rocha, na altura do rosto:\numa flecha e três pontos.\n\nNão aponta para o rio. Aponta PARALELO a ele,\npara onde a água nunca chega.\n\nQuem a fez não queria atravessar. Queria\ndescer sem se molhar.'),
   ('CAPÍTULO 2', 'O ACAMPAMENTO DO TALUDE', 'campamento', 'Ache o acampamento do talude',
    'Cordas e uma mula', 'Dois telheiros de lona pregados na parede e\numa mula amarrada curto, tranquila.\n\nYADRÉ desce pedra daqui desde os quinze.\nDiz que a passagem existe mas que este ano\no rio comeu o degrau de baixo.\n\n«Há outra. Mais acima. Eu não a encontro.»'),
   ('CAPÍTULO 3', 'A CIDADE DE BAIXO', 'ruinas', 'Atravesse as casas de pedra do fundo',
    'Ninguém saiu com pressa', 'Casas quadradas metidas no vão da parede,\ncom os tetos intactos.\n\nSem cinza, sem ossos, sem portas arrebentadas:\nsaíram andando, com tempo, levando as panelas.\n\nSabiam quando um cânion deixa de ser casa.'),
   ('CAPÍTULO 4', 'O POÇO DO FUNDO', 'oasis', 'Desça ao poço do fundo',
    'Água parada', 'O rio se alarga e se acalma num poço verde,\ntão fundo que não se vê o chão.\n\nDo outro lado, a parede tem DEGRAUS.\nEsculpidos. Vão até o topo.\n\nE três desmoronamentos os cobrem.'),
   ('CAPÍTULO 5', 'OS TRÊS DESMORONAMENTOS', 'oasis', 'Limpe os 3 desmoronamentos da escada', True,
    'A escada inteira', 'Pedra por pedra. As grandes vão para a água,\nas pequenas para o monte.\n\nE aparece: uma escada de mil anos, de um metro\nde largura, subindo colada à parede\naté a borda.\n\nO gado vai passar um a um. Mas vai passar.'),
   ('CAPÍTULO 6', 'O BALCÃO', 'cresta', 'Suba à boca do cânion e faça o sinal', True,
    'FIM', 'Da boca do cânion se vê a borda de cima,\npequenininha, com noventa pontos parados.\n\nAcende o trapo de óleo e o gira três vezes:\nDESÇAM, UM A UM, PELO LESTE.\n\nUm ponto se separa da fila. Depois outro.\nDepois a fila inteira, em ordem, começando a\ndescer por uma escada que não estava lá.\n\nCÂNION — fim da história.')],
 ],
 'npc': [
  {'tamar': ['—'],
   'yadre': ['Bajo piedra de acá desde los quince años.\nNunca vi el río tan alto en el séptimo mes.\n\nSi encontrás la escalera vieja, gritá.',
             'La mula se llama PACIENCIA y es un chiste\nque hizo mi padre y ya no tiene gracia.\n\nElla sabe el camino mejor que yo.'],
   'nekbet': ['Yo no bajé a buscar el paso. Bajé a copiar\nlas manos de la cueva antes de que el agua\nse las lleve.\n\nSon trescientas. Ninguna es igual a otra.',
              'Puse mi mano al lado de una. Encaja.\n\nMil años y la mano es la misma mano.'],
   'muleta': ['*resopla*\nLa mula te empuja con el hocico hacia el este\ny se queda mirándote.',
              'PACIENCIA no se mueve. Mira el agua, mira la\npared, y apoya la pata en el mismo lugar\ntres veces.'],
   'orfeo': ['El río sube de noche y baja al mediodía.\nSiempre. Desde que tengo memoria.\n\nSi vas a cruzar, cruzá cuando el sol pega\narriba de las agujas.'],
   'lira': ['Estoy contando las lajas grabadas.\nVoy por treinta y siete y me faltan las de\narriba, que no llego.\n\nSi juntás alguna, traéla. Las anoto.']},
  {'tamar': ['—'],
   'yadre': ['I have brought stone down from here since I\nwas fifteen. Never saw the river this high\nin the seventh month.\n\nIf you find the old stair, shout.',
             'The mule is called PATIENCE. It was my father’s\njoke and it stopped being funny.\n\nShe knows the way better than I do.'],
   'nekbet': ['I did not come down looking for the crossing.\nI came down to copy the hands in the cave\nbefore the water takes them.\n\nThere are three hundred. No two alike.',
              'I put my hand next to one. It fits.\n\nA thousand years and the hand is the same hand.'],
   'muleta': ['*snorts*\nThe mule pushes you east with her muzzle and\nthen just stands there looking at you.',
              'PATIENCE will not move. She looks at the water,\nlooks at the wall, and sets her hoof down in\nthe same spot three times.'],
   'orfeo': ['The river rises at night and drops at noon.\nAlways. As long as I can remember.\n\nIf you are going to cross, cross when the sun\nis over the spires.'],
   'lira': ['I am counting the carved slabs.\nI am at thirty-seven and I am missing the high\nones, I cannot reach them.\n\nIf you pick any up, bring them. I record them.']},
  {'tamar': ['—'],
   'yadre': ['Desço pedra daqui desde os quinze anos.\nNunca vi o rio tão alto no sétimo mês.\n\nSe achar a escada velha, grite.',
             'A mula se chama PACIÊNCIA e é uma piada que\nmeu pai fez e já não tem graça.\n\nEla sabe o caminho melhor que eu.'],
   'nekbet': ['Eu não desci para achar a passagem. Desci\npara copiar as mãos da caverna antes que a\nágua as leve.\n\nSão trezentas. Nenhuma igual à outra.',
              'Pus minha mão ao lado de uma. Encaixa.\n\nMil anos e a mão é a mesma mão.'],
   'muleta': ['*resopla*\nA mula te empurra com o focinho para o leste\ne fica te olhando.',
              'PACIÊNCIA não se move. Olha a água, olha a\nparede, e apoia a pata no mesmo lugar\ntrês vezes.'],
   'orfeo': ['O rio sobe de noite e baixa ao meio-dia.\nSempre. Desde que me lembro.\n\nSe vai atravessar, atravesse quando o sol\nbater acima das agulhas.'],
   'lira': ['Estou contando as lajes gravadas.\nVou na trinta e sete e faltam as de cima,\nque não alcanço.\n\nSe juntar alguma, traga. Eu anoto.']},
 ],
 'gente': [
  ('yadre', 'YADRÉ', 'campamento', -5, 6.5, 1.1, 'npc/muro.glb', 'canon', 'h'),
  ('nekbet', 'NEKBET', 'cueva', 4.5, 3.0, 2.4, 'npc/viajera.glb', 'viejo', 'h'),
  ('muleta', 'PACIENCIA', 'campamento', 5.0, 4.0, 2.2, 'npc/canelo.glb', None, 'p'),
  ('orfeo', 'ORFEO', 'vado', 3.5, -5.0, 0.4, 'npc/muro.glb', 'joven', 'h'),
  ('lira', 'LIRA', 'mirador', -4.0, 4.5, 3.1, 'npc/viajera.glb', None, 'h'),
 ],
}

# ---------------------------------------------------------------- ESTEPA ----
ESTEPA = {
 'sub': ['la estepa sin fin · llevar el rebaño al invernadero antes de la tormenta',
         'the endless steppe · get the herd to winter pasture before the storm',
         'a estepe sem fim · levar o rebanho ao inverno antes da tempestade'],
 'intro': [
  ('El día que giró el viento',
   'Sos AIGUL y tenés dieciséis años y el rebaño\nes tuyo desde ayer, cuando tu abuela dejó\nde poder montar.\n\nEsta mañana el viento giró al norte. Eso\nda ocho días, no más, antes de que la nieve\ntape el pasto hasta la primavera.\n\nEl invernadero está al sudoeste, detrás de\nlas piedras paradas. Tres días si el agua\nde la aguada sirve. Nueve si no.\n\nNo hay novena.'),
  ('The day the wind turned',
   'You are AIGUL, you are sixteen, and the herd\nhas been yours since yesterday, when your\ngrandmother stopped being able to ride.\n\nThis morning the wind turned north. That gives\neight days, no more, before the snow buries\nthe grass until spring.\n\nWinter pasture is southwest, behind the\nstanding stones. Three days if the water at\nthe spring is good. Nine if it is not.\n\nThere is no ninth.'),
  ('O dia em que o vento virou',
   'Você é AIGUL, tem dezesseis anos e o rebanho\né seu desde ontem, quando sua avó deixou de\nconseguir montar.\n\nEsta manhã o vento virou ao norte. Isso dá\noito dias, não mais, antes que a neve cubra\no pasto até a primavera.\n\nO pasto de inverno fica a sudoeste, atrás das\npedras paradas. Três dias se a água da\naguada servir. Nove se não.\n\nNão existe nono.'),
 ],
 'caps': [
  [('CAPÍTULO 1', 'EL MOJÓN DE CRIN', 'mojon', 'Llegá al mojón de crin',
    'Pelo trenzado', 'Un palo hincado con crin de caballo trenzada,\ntodavía sin decolorar.\n\nAlguien pasó por acá esta semana y dejó dicho\nque el pasto del oeste ya está pisado.\n\nHay que abrirse más al sur. Más camino,\npero pasto entero.'),
   ('CAPÍTULO 2', 'EL CAMPAMENTO DE FIELTRO', 'campamento', 'Encontrá el campamento de fieltro',
    'Una yurta y una discusión', 'Una yurta sola, con el humo saliendo derecho:\nno hay viento acá abajo.\n\nBEKZAT dice que el paso del sur está bien\npero que la aguada de las piedras se salobró\ny el ganado no la va a tomar.\n\nSu mujer dice que sí la va a tomar. Están\nen eso desde ayer.'),
   ('CAPÍTULO 3', 'LAS PIEDRAS PARADAS', 'ruinas', 'Cruzá el círculo de piedras paradas',
    'Doce piedras y una caída', 'Doce piedras más altas que un jinete, en\ncírculo, mirando al centro.\n\nY una tirada, la treceava, con la cara\ngrabada de líneas: es un MAPA. Los ríos que\nya no corren, marcados como si corrieran.\n\nAcá se juntaban a decidir por dónde pasar.'),
   ('CAPÍTULO 4', 'LA AGUADA', 'oasis', 'Bajá a la hondonada de la aguada',
    'Salobre', 'La aguada está donde tenía que estar y tiene\nagua. Mucha.\n\nMetés el dedo y la lengua: salada. Un caño\nde sal subió con la sequía y arruinó la\nvertiente.\n\nBEKZAT tenía razón. Y el ganado no toma sal.'),
   ('CAPÍTULO 5', 'LAS TRES ZANJAS', 'oasis', 'Abrí las 3 zanjas para desviar la vertiente', True,
    'Agua dulce arriba', 'Se cava alto, donde la vertiente todavía es\nlimpia, y se la lleva por afuera del caño\nde sal. Tres zanjas cortas.\n\nEl agua sale turbia y después clara. Metés\nel dedo: dulce.\n\nLa primera oveja toma. Después toman todas.'),
   ('CAPÍTULO 6', 'LA LOMA DEL VIGÍA', 'cresta', 'Subí a la loma del vigía y armá la baliza', True,
    'FIN', 'Desde la loma se ve el invernadero: verde\noscuro, hondo, al abrigo de la loma grande.\n\nArmás la baliza de crin y grasa y prende con\nun humo negro que se ve desde el norte.\n\nEn el horizonte hay una línea blanca que\navanza. Va a llegar mañana.\n\nY mañana el rebaño está adentro.\n\nESTEPA — fin de la historia.')],
  [('CHAPTER 1', 'THE HORSEHAIR MARKER', 'mojon', 'Reach the horsehair marker',
    'Braided hair', 'A stake driven in with braided horsehair on it,\nnot yet bleached by the sun.\n\nSomeone came through this week and left word\nthat the western grass is already grazed down.\n\nWe have to swing further south. More walking,\nbut whole grass.'),
   ('CHAPTER 2', 'THE FELT CAMP', 'campamento', 'Find the felt camp',
    'A yurt and an argument', 'One lone yurt, smoke rising dead straight:\nthere is no wind down here.\n\nBEKZAT says the southern route is fine but the\nspring by the stones has gone brackish and the\nherd will not drink it.\n\nHis wife says they will drink it. They have\nbeen at this since yesterday.'),
   ('CHAPTER 3', 'THE STANDING STONES', 'ruinas', 'Cross the ring of standing stones',
    'Twelve stones and a fallen one', 'Twelve stones taller than a rider, in a ring,\nall facing the centre.\n\nAnd one on the ground, the thirteenth, its face\ncut with lines: it is a MAP. Rivers that no\nlonger run, marked as if they did.\n\nThis is where they met to decide the route.'),
   ('CHAPTER 4', 'THE SPRING', 'oasis', 'Go down into the spring hollow',
    'Brackish', 'The spring is where it should be and it has\nwater. Plenty.\n\nYou dip a finger and taste: salt. A salt seam\nrose with the drought and ruined the flow.\n\nBEKZAT was right. And cattle do not drink salt.'),
   ('CHAPTER 5', 'THE THREE DITCHES', 'oasis', 'Open the 3 ditches to divert the flow', True,
    'Sweet water higher up', 'You dig high, where the flow is still clean,\nand lead it around the salt seam.\nThree short ditches.\n\nThe water comes out cloudy, then clear.\nYou dip a finger: sweet.\n\nThe first ewe drinks. Then they all drink.'),
   ('CHAPTER 6', 'THE WATCH HILL', 'cresta', 'Climb the watch hill and build the beacon', True,
    'THE END', 'From the hill you can see the winter pasture:\ndark green, deep, sheltered by the big ridge.\n\nYou build the beacon of hair and fat and it\ncatches with a black smoke visible from the north.\n\nOn the horizon there is a white line coming.\nIt will arrive tomorrow.\n\nAnd tomorrow the herd is inside.\n\nSTEPPE — end of the story.')],
  [('CAPÍTULO 1', 'O MARCO DE CRINA', 'mojon', 'Chegue ao marco de crina',
    'Pelo trançado', 'Uma estaca fincada com crina de cavalo\ntrançada, ainda sem desbotar.\n\nAlguém passou por aqui esta semana e deixou\ndito que o pasto do oeste já está pisado.\n\nTem que abrir mais ao sul. Mais caminho,\nmas pasto inteiro.'),
   ('CAPÍTULO 2', 'O ACAMPAMENTO DE FELTRO', 'campamento', 'Ache o acampamento de feltro',
    'Uma iurta e uma discussão', 'Uma iurta sozinha, com a fumaça saindo reta:\nnão há vento aqui embaixo.\n\nBEKZAT diz que a rota do sul está boa mas que\na aguada das pedras salobrou e o gado não\nvai beber.\n\nA mulher dele diz que vai beber. Estão\nnisso desde ontem.'),
   ('CAPÍTULO 3', 'AS PEDRAS PARADAS', 'ruinas', 'Atravesse o círculo de pedras paradas',
    'Doze pedras e uma caída', 'Doze pedras mais altas que um cavaleiro, em\ncírculo, olhando para o centro.\n\nE uma no chão, a décima terceira, com a face\ngravada de linhas: é um MAPA. Rios que já não\ncorrem, marcados como se corressem.\n\nAqui se reuniam para decidir por onde passar.'),
   ('CAPÍTULO 4', 'A AGUADA', 'oasis', 'Desça à baixada da aguada',
    'Salobra', 'A aguada está onde devia e tem água. Muita.\n\nMete o dedo e a língua: salgada. Um veio de\nsal subiu com a seca e arruinou a nascente.\n\nBEKZAT tinha razão. E gado não bebe sal.'),
   ('CAPÍTULO 5', 'AS TRÊS VALAS', 'oasis', 'Abra as 3 valas para desviar a nascente', True,
    'Água doce acima', 'Cava-se alto, onde a nascente ainda é limpa,\ne leva-se por fora do veio de sal.\nTrês valas curtas.\n\nA água sai turva e depois clara. Mete o dedo:\ndoce.\n\nA primeira ovelha bebe. Depois bebem todas.'),
   ('CAPÍTULO 6', 'A COLINA DO VIGIA', 'cresta', 'Suba à colina do vigia e monte a baliza', True,
    'FIM', 'Da colina se vê o pasto de inverno: verde\nescuro, fundo, abrigado pela colina grande.\n\nMonta a baliza de crina e gordura e ela pega\ncom uma fumaça negra que se vê do norte.\n\nNo horizonte há uma linha branca avançando.\nVai chegar amanhã.\n\nE amanhã o rebanho está dentro.\n\nESTEPE — fim da história.')],
 ],
 'npc': [
  {'aigul': ['—'],
   'bekzat': ['El paso del sur está bien, te lo firmo.\nEl agua no. Probála antes de llevar el\nganado, hacéme el favor.',
              'Mi mujer dice que las ovejas toman cualquier\ncosa. Mi mujer nunca vio una oveja de sed\nal lado de agua salada.'],
   'ainur': ['Yo tejo el fieltro. Cuarenta días una yurta\nentera, si el vellón viene limpio.\n\nEsta se la estoy haciendo a mi hija, que se\ncasa cuando bajemos.'],
   'kuma': ['*ladra corto*\nEl perro sale disparado hacia el sudoeste,\nfrena, y vuelve a buscarte.',
            'KUMA junta a las ovejas sin que nadie le diga\nnada y se sienta a mirar cómo las contás.'],
   'temir': ['Vengo del norte. Allá ya nevó.\nDos dedos, pero nevó.\n\nNo pierdas un día. En serio.'],
   'saule': ['Junto las campanillas que se le caen al\nganado. Cada una suena distinto y yo sé de\nqué animal es cada una.\n\nSi encontrás alguna, es de alguien.']},
  {'aigul': ['—'],
   'bekzat': ['The southern route is fine, I will vouch for\nit. The water is not. Taste it before you\nbring the herd, do me that favour.',
              'My wife says sheep will drink anything. My wife\nhas never seen a sheep die of thirst standing\nnext to salt water.'],
   'ainur': ['I weave the felt. Forty days for a whole yurt,\nif the fleece comes in clean.\n\nThis one is for my daughter, who marries\nwhen we go down.'],
   'kuma': ['*one short bark*\nThe dog bolts southwest, stops, and comes back\nfor you.',
            'KUMA gathers the sheep without being told and\nsits down to watch you count them.'],
   'temir': ['I am coming from the north. It has snowed\nthere already.\nTwo fingers, but it snowed.\n\nDo not lose a day. I mean it.'],
   'saule': ['I collect the little bells the cattle drop.\nEach one rings different and I know which\nanimal each belongs to.\n\nIf you find one, it belongs to somebody.']},
  {'aigul': ['—'],
   'bekzat': ['A rota do sul está boa, eu assino embaixo.\nA água não. Prove antes de levar o gado,\nme faça esse favor.',
              'Minha mulher diz que ovelha bebe qualquer\ncoisa. Minha mulher nunca viu uma ovelha\nmorrer de sede ao lado de água salgada.'],
   'ainur': ['Eu teço o feltro. Quarenta dias uma iurta\ninteira, se o velo vier limpo.\n\nEsta é para minha filha, que se casa\nquando descermos.'],
   'kuma': ['*late curto*\nO cão sai disparado para sudoeste, freia,\ne volta a te buscar.',
            'KUMA junta as ovelhas sem ninguém dizer nada\ne se senta a ver como você as conta.'],
   'temir': ['Venho do norte. Lá já nevou.\nDois dedos, mas nevou.\n\nNão perca um dia. É sério.'],
   'saule': ['Junto as campainhas que caem do gado. Cada\numa soa diferente e eu sei de que animal\né cada uma.\n\nSe achar alguma, é de alguém.']},
 ],
 'gente': [
  ('bekzat', 'BEKZAT', 'campamento', -5, 6.5, 1.1, 'npc/muro.glb', 'estepa', 'h'),
  ('ainur', 'AINUR', 'campamento', 6.5, -4.5, 2.6, 'npc/viajera.glb', None, 'h'),
  ('kuma', 'KUMA', 'rebano', 4.5, 4.0, 2.2, 'npc/canelo.glb', None, 'p'),
  ('temir', 'TEMIR', 'kurgan', -4.0, 5.5, 0.7, 'npc/muro.glb', 'viejo', 'h'),
  ('saule', 'SAULE', 'pozo', 3.5, -4.0, 3.4, 'npc/viajera.glb', 'joven', 'h'),
 ],
}

# ------------------------------------------------------------- ACRÓPOLIS ----
ACROPOLIS = {
 'sub': ['el santuario sobre el mar · levantar las cinco columnas antes de la fiesta',
         'the sanctuary above the sea · raise the five columns before the feast',
         'o santuário sobre o mar · levantar as cinco colunas antes da festa'],
 'intro': [
  ('Doce días para la fiesta',
   'Sos KLEIO y sos aprendiza de cantero, que\nes una manera fina de decir que acarreás.\n\nEl temblor de la primavera tiró cinco\ncolumnas del pórtico del santuario y las\ndejó tendidas como leña.\n\nEn doce días sube la procesión. Si el pórtico\nno está en pie, la ciudad va a pensar que\nel dios se fue.\n\nTu maestro tiene ochenta años y una mano.\nVos tenés dos y el sendero de sal empieza acá.'),
  ('Twelve days to the feast',
   'You are KLEIO, a stonemason’s apprentice,\nwhich is a polite way of saying you carry.\n\nThe spring tremor threw down five columns of\nthe sanctuary portico and left them lying\nthere like firewood.\n\nIn twelve days the procession climbs up. If\nthe portico is not standing, the city will\nthink the god has left.\n\nYour master is eighty and has one working hand.\nYou have two, and the salt path starts here.'),
  ('Doze dias para a festa',
   'Você é KLEIO, aprendiz de canteiro, que é um\njeito fino de dizer que carrega.\n\nO tremor da primavera derrubou cinco colunas\ndo pórtico do santuário e as deixou deitadas\ncomo lenha.\n\nEm doze dias sobe a procissão. Se o pórtico\nnão estiver de pé, a cidade vai pensar que\no deus foi embora.\n\nSeu mestre tem oitenta anos e uma mão.\nVocê tem duas, e a trilha do sal começa aqui.'),
 ],
 'caps': [
  [('CAPÍTULO 1', 'EL HITO DE MÁRMOL', 'mojon', 'Subí al hito de mármol del sendero',
    'Una letra y una flecha', 'Un bloque de mármol a media cuesta con una\nletra y una flecha, gastadas por las sandalias\nde doscientos años de procesiones.\n\nLa flecha no va derecho al santuario. Rodea.\n\nDerecho es más corto y más resbaloso. Con\nun tambor de columna encima, importa.'),
   ('CAPÍTULO 2', 'EL CAMPAMENTO DE LOS OBREROS', 'campamento', 'Encontrá el campamento de los obreros',
    'Ocho hombres y ninguna grúa', 'Toldos de lino, un horno de cal y ocho\nhombres esperando desde hace cuatro días.\n\nHIERON, tu maestro, está sentado mirando las\ncolumnas caídas como si fueran una cuenta\nque no le cierra.\n\n«Los tambores están. Faltan las cuñas y\nfaltan las manos. Vos sos las manos.»'),
   ('CAPÍTULO 3', 'EL SANTUARIO', 'ruinas', 'Llegá a la explanada del santuario',
    'Cinco caídas, once en pie', 'Once columnas siguen paradas, blancas, con la\nluz del mar pegándoles de abajo.\n\nLas otras cinco están tendidas en el suelo,\npartidas en tambores limpios, como si alguien\nlas hubiera desarmado con cuidado.\n\nEl temblor fue prolijo. Eso ayuda.'),
   ('CAPÍTULO 4', 'LA FUENTE SAGRADA', 'oasis', 'Bajá a la fuente sagrada',
    'Agua para la cal', 'La fuente sale de la roca en un chorro fino y\ncae en una pila tallada con delfines.\n\nNo es para beber: es para la CAL. Sin agua no\nhay mortero y sin mortero los tambores no\nse asientan.\n\nDoce días. Y la pila está tapada de hojas.'),
   ('CAPÍTULO 5', 'LAS CINCO COLUMNAS', 'ruinas', 'Levantá las 5 columnas del pórtico', True,
    'De pie', 'Cuña, palanca, cuerda, cantar todos juntos\npara empujar en el mismo momento.\n\nUna. Dos. La tercera se resiste medio día.\nCuatro. Cinco.\n\nHIERON no dice nada. Pasa la mano buena por\nel fuste, de abajo hacia arriba, como se\ntoca a un animal que se portó bien.'),
   ('CAPÍTULO 6', 'EL PROMONTORIO', 'cresta', 'Subí al promontorio y encendé el pebetero', True,
    'FIN', 'El pebetero del promontorio se ve desde el\npuerto, desde las islas y desde los barcos\nque vienen de noche.\n\nLo encendés con el aceite de la primera\nprensa. Prende alto, derecho, sin humo.\n\nAbajo, en la ciudad, empiezan a encenderse\nlos otros. Uno por casa.\n\n«Ya sabés levantar una columna», dice HIERON.\n«Ahora aprendé a tallar una.»\n\nACRÓPOLIS — fin de la historia.')],
  [('CHAPTER 1', 'THE MARBLE MARKER', 'mojon', 'Climb to the marble marker on the path',
    'A letter and an arrow', 'A marble block halfway up with a letter and an\narrow on it, worn smooth by two hundred years\nof sandals.\n\nThe arrow does not go straight to the sanctuary.\nIt goes around.\n\nStraight is shorter and more slippery. With a\ncolumn drum on your back, that matters.'),
   ('CHAPTER 2', 'THE WORKERS’ CAMP', 'campamento', 'Find the workers’ camp',
    'Eight men and no crane', 'Linen awnings, a lime kiln and eight men who\nhave been waiting four days.\n\nHIERON, your master, sits looking at the fallen\ncolumns like an account that will not balance.\n\n“The drums are here. What is missing is wedges\nand hands. You are the hands.”'),
   ('CHAPTER 3', 'THE SANCTUARY', 'ruinas', 'Reach the sanctuary terrace',
    'Five down, eleven standing', 'Eleven columns are still up, white, with the\nlight off the sea hitting them from below.\n\nThe other five lie on the ground, broken into\nclean drums, as if someone had taken them\napart carefully.\n\nThe tremor was tidy. That helps.'),
   ('CHAPTER 4', 'THE SACRED SPRING', 'oasis', 'Go down to the sacred spring',
    'Water for the lime', 'The spring comes out of the rock in a thin jet\nand falls into a basin carved with dolphins.\n\nIt is not for drinking: it is for LIME. No water,\nno mortar; no mortar, the drums will not seat.\n\nTwelve days. And the basin is choked with leaves.'),
   ('CHAPTER 5', 'THE FIVE COLUMNS', 'ruinas', 'Raise the 5 columns of the portico', True,
    'Standing', 'Wedge, lever, rope, and everyone singing\ntogether so they push on the same beat.\n\nOne. Two. The third fights for half a day.\nFour. Five.\n\nHIERON says nothing. He runs his good hand up\nthe shaft, bottom to top, the way you touch\nan animal that behaved well.'),
   ('CHAPTER 6', 'THE HEADLAND', 'cresta', 'Climb the headland and light the brazier', True,
    'THE END', 'The headland brazier can be seen from the\nharbour, from the islands, and from ships\ncoming in at night.\n\nYou light it with oil from the first pressing.\nIt burns high, straight, no smoke.\n\nBelow, in the city, the others start coming on.\nOne per house.\n\n“So you can raise a column,” says HIERON.\n“Now learn to cut one.”\n\nACROPOLIS — end of the story.')],
  [('CAPÍTULO 1', 'O MARCO DE MÁRMORE', 'mojon', 'Suba ao marco de mármore da trilha',
    'Uma letra e uma flecha', 'Um bloco de mármore no meio da subida com uma\nletra e uma flecha, gastas pelas sandálias\nde duzentos anos de procissões.\n\nA flecha não vai direto ao santuário. Rodeia.\n\nDireto é mais curto e mais escorregadio. Com\num tambor de coluna nas costas, isso importa.'),
   ('CAPÍTULO 2', 'O ACAMPAMENTO DOS OPERÁRIOS', 'campamento', 'Ache o acampamento dos operários',
    'Oito homens e nenhuma grua', 'Toldos de linho, um forno de cal e oito homens\nesperando há quatro dias.\n\nHIERON, seu mestre, está sentado olhando as\ncolunas caídas como uma conta que não fecha.\n\n«Os tambores estão. Faltam as cunhas e faltam\nas mãos. Você é as mãos.»'),
   ('CAPÍTULO 3', 'O SANTUÁRIO', 'ruinas', 'Chegue à esplanada do santuário',
    'Cinco caídas, onze de pé', 'Onze colunas seguem de pé, brancas, com a luz\ndo mar batendo nelas de baixo.\n\nAs outras cinco estão deitadas no chão,\npartidas em tambores limpos, como se alguém\nas tivesse desmontado com cuidado.\n\nO tremor foi caprichoso. Isso ajuda.'),
   ('CAPÍTULO 4', 'A FONTE SAGRADA', 'oasis', 'Desça à fonte sagrada',
    'Água para a cal', 'A fonte sai da rocha num jato fino e cai numa\npia esculpida com delfins.\n\nNão é para beber: é para a CAL. Sem água não\nhá argamassa e sem argamassa os tambores\nnão assentam.\n\nDoze dias. E a pia está entupida de folhas.'),
   ('CAPÍTULO 5', 'AS CINCO COLUNAS', 'ruinas', 'Levante as 5 colunas do pórtico', True,
    'De pé', 'Cunha, alavanca, corda, e cantar todos juntos\npara empurrar no mesmo momento.\n\nUma. Duas. A terceira resiste meio dia.\nQuatro. Cinco.\n\nHIERON não diz nada. Passa a mão boa pelo\nfuste, de baixo para cima, como se toca um\nanimal que se comportou bem.'),
   ('CAPÍTULO 6', 'O PROMONTÓRIO', 'cresta', 'Suba ao promontório e acenda o braseiro', True,
    'FIM', 'O braseiro do promontório se vê do porto, das\nilhas e dos navios que chegam de noite.\n\nVocê o acende com o azeite da primeira prensa.\nPega alto, reto, sem fumaça.\n\nEmbaixo, na cidade, começam a acender os\noutros. Um por casa.\n\n«Já sabe levantar uma coluna», diz HIERON.\n«Agora aprenda a esculpir uma.»\n\nACRÓPOLE — fim da história.')],
 ],
 'npc': [
  {'kleio': ['—'],
   'hieron': ['Ochenta años y una mano. La otra la dejé\nen un bloque en el año del cometa.\n\nPor eso ahora enseño en vez de tallar.',
              'Una columna no se levanta con fuerza. Se\nlevanta con el momento justo y con ocho\npersonas contando igual.\n\nLa fuerza sobra siempre. El momento no.'],
   'thalia': ['Yo hago la cal. Piedra al horno tres días y\nsale polvo que muerde.\n\nSi te salpica, agua, mucha agua, y no te\nfrotes los ojos.'],
   'nikias': ['Talló el friso del lado del mar mi bisabuelo.\nSe cayó entero con el temblor.\n\nJunto los pedazos. Alguna vez alguien va a\nsaber cómo iba.'],
   'argos': ['*mueve la cola*\nEl perro del campamento te sigue hasta el\nborde del acantilado y ahí frena en seco.',
             'ARGOS duerme arriba de la lona de las\nherramientas y no la deja tocar a nadie\nque no sea del gremio.'],
   'phoibe': ['Subo el agua desde la fuente en dos cántaros.\nCatorce viajes por día.\n\nCuando la pila está tapada de hojas, veinte.']},
  {'kleio': ['—'],
   'hieron': ['Eighty years and one hand. I left the other\nin a block the year of the comet.\n\nThat is why I teach now instead of cutting.',
              'A column is not raised with strength. It is\nraised with the right moment and eight people\ncounting the same.\n\nStrength is always spare. The moment is not.'],
   'thalia': ['I make the lime. Stone in the kiln three days\nand out comes a powder that bites.\n\nIf it splashes you: water, a lot of water,\nand do not rub your eyes.'],
   'nikias': ['My great-grandfather cut the seaward frieze.\nIt came down whole in the tremor.\n\nI am collecting the pieces. Some day someone\nwill work out how it went.'],
   'argos': ['*wags*\nThe camp dog follows you to the cliff edge and\nstops dead there.',
             'ARGOS sleeps on top of the tool canvas and will\nnot let anyone who is not guild touch it.'],
   'phoibe': ['I carry the water up from the spring in two\njars. Fourteen trips a day.\n\nWhen the basin is choked with leaves, twenty.']},
  {'kleio': ['—'],
   'hieron': ['Oitenta anos e uma mão. A outra deixei num\nbloco no ano do cometa.\n\nPor isso agora ensino em vez de esculpir.',
              'Uma coluna não se levanta com força. Levanta-se\ncom o momento certo e com oito pessoas\ncontando igual.\n\nForça sempre sobra. O momento não.'],
   'thalia': ['Eu faço a cal. Pedra no forno três dias e sai\num pó que morde.\n\nSe te espirrar: água, muita água, e não\nesfregue os olhos.'],
   'nikias': ['Meu bisavô esculpiu o friso do lado do mar.\nCaiu inteiro com o tremor.\n\nJunto os pedaços. Algum dia alguém vai saber\ncomo era.'],
   'argos': ['*abana o rabo*\nO cão do acampamento te segue até a borda do\npenhasco e ali freia seco.',
             'ARGOS dorme em cima da lona das ferramentas e\nnão deixa ninguém que não seja do ofício\ntocar nela.'],
   'phoibe': ['Subo a água da fonte em dois cântaros.\nCatorze viagens por dia.\n\nQuando a pia está entupida de folhas, vinte.']},
 ],
 'gente': [
  ('hieron', 'HIERON', 'campamento', -5, 6.5, 1.1, 'npc/muro.glb', 'acropolis', 'h'),
  ('thalia', 'THALIA', 'campamento', 6.0, -5.0, 2.5, 'npc/viajera.glb', None, 'h'),
  ('argos', 'ARGOS', 'campamento', 4.5, 4.0, 2.2, 'npc/canelo.glb', None, 'p'),
  ('nikias', 'NIKIAS', 'teatro', -4.5, 4.0, 0.6, 'npc/muro.glb', 'viejo', 'h'),
  ('phoibe', 'PHOIBE', 'cisterna', 3.5, -4.5, 3.2, 'npc/viajera.glb', 'joven', 'h'),
 ],
}

# --------------------------------------------------------------- SECUOYA ----
SECUOYA = {
 'sub': ['el bosque de gigantes · encontrar el árbol madre antes del corte',
         'the forest of giants · find the mother tree before the cut',
         'a floresta de gigantes · achar a árvore mãe antes do corte'],
 'intro': [
  ('Tres días antes del corte',
   'Sos WENU y hasta el mes pasado marcabas\nárboles para cortar. Ahora marcás uno para\nque NO lo corten.\n\nEn el bosque hay una secuoya que sembró todas\nlas demás: sus piñas son las únicas del valle\nque germinan. Nadie sabe cuál es.\n\nEl aserradero empieza por el norte en tres\ndías y no pregunta.\n\nSi encontrás el árbol madre y lo marcás,\nqueda en pie. Esa es toda la ley que hay.'),
  ('Three days before the cut',
   'You are WENU and until last month you marked\ntrees to be felled. Now you are marking one\nso it will NOT be.\n\nSomewhere in this forest there is a redwood\nthat seeded all the others: its cones are the\nonly ones in the valley that germinate.\nNobody knows which tree it is.\n\nThe mill starts in the north in three days\nand it does not ask.\n\nIf you find the mother tree and mark it, it\nstays. That is all the law there is.'),
  ('Três dias antes do corte',
   'Você é WENU e até o mês passado marcava\nárvores para cortar. Agora marca uma para\nque NÃO a cortem.\n\nNa floresta há uma sequoia que semeou todas\nas outras: suas pinhas são as únicas do vale\nque germinam. Ninguém sabe qual é.\n\nA serraria começa pelo norte em três dias\ne não pergunta.\n\nSe achar a árvore mãe e marcá-la, fica de pé.\nEssa é toda a lei que existe.'),
 ],
 'caps': [
  [('CAPÍTULO 1', 'EL MOJÓN DE MUSGO', 'mojon', 'Entrá al bosque hasta el mojón de musgo',
    'Una marca vieja', 'Una piedra con una muesca tapada de musgo.\nLa raspás y aparece una fecha de hace\ncuarenta años.\n\nAlguien ya buscó el árbol madre antes.\nY dejó marcas para el que viniera atrás.\n\nHay que seguir las muescas, no los caminos.'),
   ('CAPÍTULO 2', 'EL CAMPAMENTO DE LA PARTIDA', 'campamento', 'Encontrá el campamento de la partida',
    'Dos catres y un herbario', 'Una carpa, dos catres y una mesa con hojas\nprensadas entre papeles.\n\nMILLARAY mide troncos para el aserradero de\ndía y de noche dibuja las hojas de todo lo\nque va a desaparecer.\n\n«Las piñas fértiles pesan distinto», dice.\n«Si juntás alguna, traéla. Yo las pruebo.»'),
   ('CAPÍTULO 3', 'EL CLARO DEL ÁRBOL MADRE', 'ruinas', 'Llegá al claro grande del bosque',
    'Uno que no está', 'El claro es enorme y redondo, con luz cayendo\nderecho al suelo, y ningún árbol adentro.\n\nEn el medio hay un TOCÓN. Cuatro metros de\nancho, gris, con anillos que no se acaban.\n\nCortaron algo acá. Hace mucho.\n\nY alrededor del tocón, en corro, están los\ndiez árboles más grandes del bosque.'),
   ('CAPÍTULO 4', 'EL REMANSO', 'oasis', 'Bajá al remanso del arroyo',
    'El agua sabe', 'El arroyo se aquieta en un remanso oscuro y\nel fondo está tapado de piñas.\n\nMILLARAY tenía razón: las que flotan están\nvacías, las que se hunden tienen semilla.\n\nSe hunden las que bajaron desde el mismo\nlugar. Basta seguir el arroyo hacia arriba.'),
   ('CAPÍTULO 5', 'LOS TRES ÁRBOLES', 'ruinas', 'Probá las piñas de los 3 árboles del corro', True,
    'El tercero', 'Al primero se le caen piñas huecas.\nAl segundo, huecas.\n\nAl tercero, no: las suyas se hunden como\npiedras y tienen la semilla dura y aceitosa.\n\nEl tocón del medio era su padre. Este árbol\nes el hijo que quedó, y sembró todo lo demás.'),
   ('CAPÍTULO 6', 'LA LOMA DEL HELECHO', 'cresta', 'Subí a la loma y clavá la marca azul', True,
    'FIN', 'La marca azul se clava a la altura del pecho,\ncon tres golpes, del lado del camino, para\nque la vea el que venga con la sierra.\n\nNo se discute una marca azul. Se rodea.\n\nDesde la loma se oye el aserradero empezando\nal norte. Va a llegar hasta acá y va a doblar.\n\nMILLARAY guarda tres piñas en un frasco y\nescribe la fecha.\n\nSECUOYA — fin de la historia.')],
  [('CHAPTER 1', 'THE MOSS MARKER', 'mojon', 'Enter the forest as far as the moss marker',
    'An old mark', 'A stone with a notch buried in moss.\nYou scrape it clear and a date appears:\nforty years ago.\n\nSomeone looked for the mother tree before.\nAnd left marks for whoever came after.\n\nFollow the notches, not the trails.'),
   ('CHAPTER 2', 'THE SURVEY CAMP', 'campamento', 'Find the survey camp',
    'Two cots and a herbarium', 'A tent, two cots, and a table with leaves\npressed between sheets of paper.\n\nMILLARAY measures trunks for the mill by day\nand by night draws the leaves of everything\nthat is about to be gone.\n\n“Fertile cones weigh differently,” she says.\n“If you pick any up, bring them. I test them.”'),
   ('CHAPTER 3', 'THE MOTHER TREE CLEARING', 'ruinas', 'Reach the big clearing in the forest',
    'One that is not there', 'The clearing is huge and round, with light\nfalling straight to the ground, and no tree\nstanding inside it.\n\nIn the middle there is a STUMP. Four metres\nacross, grey, with rings that do not end.\n\nSomething was cut here. Long ago.\n\nAnd around the stump, in a ring, stand the ten\nlargest trees in the forest.'),
   ('CHAPTER 4', 'THE STILL POOL', 'oasis', 'Go down to the still pool of the creek',
    'The water knows', 'The creek settles into a dark pool and the\nbottom is carpeted with cones.\n\nMILLARAY was right: the ones that float are\nempty, the ones that sink hold seed.\n\nThe ones that sink all came down from the same\nplace. Just follow the creek up.'),
   ('CHAPTER 5', 'THE THREE TREES', 'ruinas', 'Test the cones of the 3 trees in the ring', True,
    'The third one', 'The first drops hollow cones.\nThe second, hollow.\n\nThe third does not: its cones sink like stones\nand the seed inside is hard and oily.\n\nThe stump in the middle was its parent. This\ntree is the child that was left, and it seeded\neverything else.'),
   ('CHAPTER 6', 'THE FERN HILL', 'cresta', 'Climb the hill and drive in the blue mark', True,
    'THE END', 'The blue mark goes in at chest height, three\nblows, on the road side, so the one coming\nwith the saw will see it.\n\nA blue mark is not argued with. It is gone around.\n\nFrom the hill you can hear the mill starting up\nin the north. It will come this far and turn.\n\nMILLARAY puts three cones in a jar and writes\nthe date on it.\n\nREDWOOD — end of the story.')],
  [('CAPÍTULO 1', 'O MARCO DE MUSGO', 'mojon', 'Entre na floresta até o marco de musgo',
    'Uma marca velha', 'Uma pedra com um entalhe coberto de musgo.\nVocê o raspa e aparece uma data de quarenta\nanos atrás.\n\nAlguém já procurou a árvore mãe antes.\nE deixou marcas para quem viesse depois.\n\nHá que seguir os entalhes, não os caminhos.'),
   ('CAPÍTULO 2', 'O ACAMPAMENTO DA EQUIPE', 'campamento', 'Ache o acampamento da equipe',
    'Dois catres e um herbário', 'Uma tenda, dois catres e uma mesa com folhas\nprensadas entre papéis.\n\nMILLARAY mede troncos para a serraria de dia\ne de noite desenha as folhas de tudo o que\nvai desaparecer.\n\n«As pinhas férteis pesam diferente», diz ela.\n«Se juntar alguma, traga. Eu testo.»'),
   ('CAPÍTULO 3', 'A CLAREIRA DA ÁRVORE MÃE', 'ruinas', 'Chegue à clareira grande da floresta',
    'Uma que não está', 'A clareira é enorme e redonda, com luz caindo\nreta ao chão, e nenhuma árvore dentro.\n\nNo meio há um TOCO. Quatro metros de largura,\ncinza, com anéis que não terminam.\n\nCortaram algo aqui. Há muito tempo.\n\nE em volta do toco, em roda, estão as dez\nárvores maiores da floresta.'),
   ('CAPÍTULO 4', 'O REMANSO', 'oasis', 'Desça ao remanso do riacho',
    'A água sabe', 'O riacho se acalma num remanso escuro e o\nfundo está coberto de pinhas.\n\nMILLARAY tinha razão: as que flutuam estão\nvazias, as que afundam têm semente.\n\nAs que afundam desceram todas do mesmo lugar.\nBasta seguir o riacho para cima.'),
   ('CAPÍTULO 5', 'AS TRÊS ÁRVORES', 'ruinas', 'Teste as pinhas das 3 árvores da roda', True,
    'A terceira', 'Da primeira caem pinhas ocas.\nDa segunda, ocas.\n\nDa terceira, não: as dela afundam como pedras\ne a semente é dura e oleosa.\n\nO toco do meio era seu pai. Esta árvore é o\nfilho que sobrou, e semeou todo o resto.'),
   ('CAPÍTULO 6', 'A COLINA DA SAMAMBAIA', 'cresta', 'Suba à colina e fixe a marca azul', True,
    'FIM', 'A marca azul se prega na altura do peito, com\ntrês golpes, do lado da estrada, para que\nveja quem vier com a serra.\n\nMarca azul não se discute. Se contorna.\n\nDa colina se ouve a serraria começando ao\nnorte. Vai chegar até aqui e vai virar.\n\nMILLARAY guarda três pinhas num frasco e\nescreve a data.\n\nSEQUOIA — fim da história.')],
 ],
 'npc': [
  {'wenu': ['—'],
   'millaray': ['Marco troncos de día. De noche dibujo las\nhojas de todo lo que va a desaparecer.\n\nAlguien tiene que quedarse con el dibujo.',
                'Las piñas fértiles pesan distinto. Se hunden.\nLas vacías flotan y se van con el arroyo.\n\nEs el truco más viejo que hay y funciona.'],
   'anka': ['Yo manejo la sierra grande. Y no, no me\ngusta hablar de eso.\n\nSi clavás la marca azul, doblo. Palabra.'],
   'kuyen': ['Subí al nido alto a ver si los cóndores\nvolvían este año.\n\nVolvieron. Dos. En el mismo árbol del año\npasado, que ojalá sea el que buscás.'],
   'nahuel': ['*olfatea*\nEl perro te empuja la mano y sale trotando\narroyo arriba sin mirar atrás.',
              'NAHUEL cava en la hojarasca, saca una piña,\nla suelta a tus pies y se sienta.'],
   'rayen': ['Estoy contando los anillos del tocón del\nclaro. Voy por mil doscientos y todavía\nno llego al centro.\n\nEse árbol vio todo esto vacío.']},
  {'wenu': ['—'],
   'millaray': ['I mark trunks by day. By night I draw the\nleaves of everything that is going to be gone.\n\nSomebody has to be left holding the drawing.',
                'Fertile cones weigh differently. They sink.\nThe empty ones float and go off with the creek.\n\nIt is the oldest trick there is and it works.'],
   'anka': ['I run the big saw. And no, I do not like\ntalking about it.\n\nIf you drive in the blue mark, I turn. My word.'],
   'kuyen': ['I climbed to the high nest to see whether the\ncondors came back this year.\n\nThey did. Two of them. In the same tree as\nlast year, which I hope is the one you want.'],
   'nahuel': ['*sniffs*\nThe dog nudges your hand and trots off up the\ncreek without looking back.',
              'NAHUEL digs in the leaf litter, pulls out a\ncone, drops it at your feet and sits down.'],
   'rayen': ['I am counting the rings on the stump in the\nclearing. I am at twelve hundred and I still\nhave not reached the centre.\n\nThat tree saw all this empty.']},
  {'wenu': ['—'],
   'millaray': ['Marco troncos de dia. De noite desenho as\nfolhas de tudo o que vai desaparecer.\n\nAlguém tem que ficar com o desenho.',
                'As pinhas férteis pesam diferente. Afundam.\nAs vazias flutuam e vão com o riacho.\n\nÉ o truque mais velho que existe e funciona.'],
   'anka': ['Eu opero a serra grande. E não, não gosto\nde falar sobre isso.\n\nSe fixar a marca azul, eu viro. Palavra.'],
   'kuyen': ['Subi ao nido alto para ver se os condores\nvoltavam este ano.\n\nVoltaram. Dois. Na mesma árvore do ano\npassado, que espero seja a que procura.'],
   'nahuel': ['*fareja*\nO cão empurra sua mão e sai trotando riacho\nacima sem olhar para trás.',
              'NAHUEL cava na folhagem, tira uma pinha,\nsolta aos seus pés e se senta.'],
   'rayen': ['Estou contando os anéis do toco da clareira.\nVou nos mil e duzentos e ainda não cheguei\nao centro.\n\nAquela árvore viu tudo isto vazio.']},
 ],
 'gente': [
  ('millaray', 'MILLARAY', 'campamento', -5, 6.5, 1.1, 'npc/viajera.glb', 'secuoya', 'h'),
  ('anka', 'ANKA', 'quemado', 5.0, -4.5, 2.4, 'npc/muro.glb', 'viejo', 'h'),
  ('nahuel', 'NAHUEL', 'campamento', 5.0, 4.0, 2.2, 'npc/canelo.glb', None, 'p'),
  ('kuyen', 'KUYEN', 'nido', -4.0, 5.0, 0.5, 'npc/viajera.glb', 'joven', 'h'),
  ('rayen', 'RAYEN', 'tronco', 4.0, -4.0, 3.0, 'npc/muro.glb', None, 'h'),
 ],
}

MUNDOS = {'canon': CANON, 'estepa': ESTEPA, 'acropolis': ACROPOLIS, 'secuoya': SECUOYA}
