// All player-visible strings. Switching language is a data change only.
export const STR = {
  es: {
    loading: "CARGANDO",
    tapToStart: "TOCA O PULSA PARA EMPEZAR",
    play: "JUGAR",
    language: "IDIOMA: ESPAÑOL",
    sound_on: "SONIDO: SÍ",
    sound_off: "SONIDO: NO",
    fx_on: "EFECTOS: ALTOS",
    fx_off: "EFECTOS: SUAVES",
    selectTrack: "ELIGE PISTA",
    locked: "BLOQUEADA",
    lockedHint: "Termina en el podio de la pista anterior",
    best: "RÉCORD",
    noBest: "SIN RÉCORD",
    laps: "VUELTAS",
    back: "VOLVER",
    go: "¡YA!",
    lap: "VUELTA",
    finalLap: "¡ÚLTIMA VUELTA!",
    pos: "POS",
    time: "TIEMPO",
    nitro: "NITRO",
    kmh: "km/h",
    paused: "PAUSA",
    resume: "SEGUIR",
    restart: "REINICIAR",
    exit: "SALIR",
    finished: "¡META!",
    results: "RESULTADOS",
    position: "POSICIÓN",
    totalTime: "TIEMPO TOTAL",
    bestLap: "MEJOR VUELTA",
    newRecord: "¡NUEVO RÉCORD!",
    unlocked: "¡PISTA DESBLOQUEADA!",
    retry: "REINTENTAR",
    next: "SIGUIENTE",
    menu: "MENÚ",
    wrecked: "¡CHOQUE!",
    pickupNitro: "+NITRO",
    controlsTitle: "CONTROLES",
    controlsKeys: "Flechas o WASD para conducir · ESPACIO nitro · P pausa",
    controlsPad: "Mando: stick para girar · RT gas · LT freno · A nitro",
    controlsTouch: "Táctil: flechas para girar · GAS / FRENO / NITRO",
    gas: "GAS",
    brake: "FRENO",
    posOf: "de",
    track1: "COSTA NEÓN",
    track2: "CAÑÓN VIOLETA",
    track3: "AUTOPISTA MEDIANOCHE",
    tagline: "Carreras arcade al atardecer",
    madeWith: "Assets generados con Higgsfield",
  },
  en: {
    loading: "LOADING",
    tapToStart: "TAP OR PRESS TO START",
    play: "PLAY",
    language: "LANGUAGE: ENGLISH",
    sound_on: "SOUND: ON",
    sound_off: "SOUND: OFF",
    fx_on: "EFFECTS: HIGH",
    fx_off: "EFFECTS: SOFT",
    selectTrack: "SELECT TRACK",
    locked: "LOCKED",
    lockedHint: "Finish on the podium of the previous track",
    best: "BEST",
    noBest: "NO RECORD",
    laps: "LAPS",
    back: "BACK",
    go: "GO!",
    lap: "LAP",
    finalLap: "FINAL LAP!",
    pos: "POS",
    time: "TIME",
    nitro: "NITRO",
    kmh: "km/h",
    paused: "PAUSED",
    resume: "RESUME",
    restart: "RESTART",
    exit: "QUIT",
    finished: "FINISH!",
    results: "RESULTS",
    position: "POSITION",
    totalTime: "TOTAL TIME",
    bestLap: "BEST LAP",
    newRecord: "NEW RECORD!",
    unlocked: "TRACK UNLOCKED!",
    retry: "RETRY",
    next: "NEXT",
    menu: "MENU",
    wrecked: "CRASH!",
    pickupNitro: "+NITRO",
    controlsTitle: "CONTROLS",
    controlsKeys: "Arrows or WASD to drive · SPACE nitro · P pause",
    controlsPad: "Gamepad: stick to steer · RT gas · LT brake · A nitro",
    controlsTouch: "Touch: arrows to steer · GAS / BRAKE / NITRO",
    gas: "GAS",
    brake: "BRAKE",
    posOf: "of",
    track1: "NEON COAST",
    track2: "VIOLET CANYON",
    track3: "MIDNIGHT HIGHWAY",
    tagline: "Arcade racing into the sunset",
    madeWith: "Assets generated with Higgsfield",
  },
};
